# Generated by Django 5.2.7 on 2025-10-31 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorydb',
            old_name='category_name',
            new_name='Category_name',
        ),
    ]
