# Generated by Django 5.2.7 on 2025-11-12 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_name', models.CharField(blank=True, max_length=100, null=True)),
                ('User_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Subject', models.CharField(blank=True, max_length=100, null=True)),
                ('Message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
